### ISSUE TITLE
can not Install fairseq

### ISSUE THREAD

**Issue by conheaven** [ductuantruong/tcm_add#1]
run:pip install --editable ./

Error:error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/data1/khw/miniconda3/envs/tcm_add/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/data1/khw/miniconda3/envs/tcm_add/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data1/khw/miniconda3/envs/tcm_add/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-install-jevihipr/pyyaml_69bc2f56f3354b708e8226cde1543985/packaging/_pyyaml_pep517.py", line 47, in _expose_config_settings
          return real_method(*args, **kwargs)
        File "/tmp/pip-build-env-gjbu35i9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-gjbu35i9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gjbu35i9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<fstring>", line 1
          (self.include_dirs=)
                            ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ductuantruong** [comment]
Hi @conheaven,

Have you git checkout the a54021305d6b3c commit of the fairseq repo before installing it?

**Comment by conheaven** [comment]
> Hi @conheaven,
> 
> Have you git checkout the a54021305d6b3c commit of the fairseq repo before installing it?

sure
here's error


(tcm) khw@cxhpc-NF5468M6:/data1/khw/Deepfake_detection/tcm_add$ cd fairseq_dir
git checkout a54021305d6b3c
Note: switching to 'a54021305d6b3c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a5402130 formatting fix (#2816)
(tcm) khw@cxhpc-NF5468M6:/data1/khw/Deepfake_detection/tcm_add/fairseq_dir$ pip install --editable ./
Obtaining file:///data1/khw/Deepfake_detection/tcm_add/fairseq_dir
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages (from fairseq==1.0.0a0+a540213) (1.21.6)
Requirement already satisfied: torchaudio>=0.8.0 in /data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages (from fairseq==1.0.0a0+a540213) (0.8.1)
Collecting regex
  Using cached regex-2024.4.16-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (761 kB)
Collecting bitarray
  Using cached bitarray-2.9.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
Requirement already satisfied: torch in /data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages (from fairseq==1.0.0a0+a540213) (1.8.1+cu111)
Collecting omegaconf<2.1
  Using cached omegaconf-2.0.6-py3-none-any.whl (36 kB)
Collecting tqdm
  Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Collecting sacrebleu>=1.4.12
  Using cached sacrebleu-2.4.2-py3-none-any.whl (106 kB)
Collecting cython
  Using cached Cython-3.0.10-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Requirement already satisfied: cffi in /data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages (from fairseq==1.0.0a0+a540213) (1.15.1)
Collecting hydra-core<1.1,>=1.0.7
  Using cached hydra_core-1.0.7-py3-none-any.whl (123 kB)
Requirement already satisfied: importlib-resources in /data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages (from hydra-core<1.1,>=1.0.7->fairseq==1.0.0a0+a540213) (5.12.0)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4-python3-runtime-4.8.tar.gz (112 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: typing-extensions in /data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages (from omegaconf<2.1->fairseq==1.0.0a0+a540213) (4.7.1)
Collecting PyYAML>=5.1.*
  Using cached pyyaml-6.0.2rc1.tar.gz (130 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data1/khw/miniconda3/envs/tcm/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-install-o7zso8dr/pyyaml_7d3a7c45827c49108fb15c7ac07e8942/packaging/_pyyaml_pep517.py", line 47, in _expose_config_settings
          return real_method(*args, **kwargs)
        File "/tmp/pip-build-env-4e28m12o/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-4e28m12o/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-4e28m12o/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<fstring>", line 1
          (self.include_dirs=)
                            ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ductuantruong** [comment]
Hi @conheaven,

Can I ask for your Python version? Is it 3.7.16?

**Comment by conheaven** [comment]
yes  3.7.16



---- Replied Message ----
| From | Truong Duc ***@***.***> |
| Date | 08/01/2024 12:50 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ductuantruong/tcm_add] can not Install fairseq (Issue #1) |

Hi @conheaven,

Can I ask for your Python version? Is it 3.7.16?

**Comment by ductuantruong** [comment]
Could you try to install with the pip version 22.3.1? If this error still happens, please try with Python 3.8.

**Comment by conheaven** [comment]
> Could you try to install with the pip version 22.3.1? If this error still happens, please try with Python 3.8.

it worked, thank you very much！

**Comment by conheaven** [comment]
> Could you try to install with the pip version 22.3.1? If this error still happens, please try with Python 3.8.

it worked, thank you very much！

**Comment by ductuantruong** [comment]
Happy to help! if you find the work helpful, a star to this repo is much appreciated.
